### ISSUE TITLE
ErrorException in compiled.php

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [mbarwick83/shorty#1]
Hello,
i'm having issues with the deployment of my app using Shorty.
Using:
laravel 5.2
PHP Version 5.5.16
http://prntscr.com/bivgeq

i followed the instructions, locally works as expected. The issue is only on my env servers.
running composer install does install and i can see the folder with the code.

It may be an issue with case sensitive, (i've already tried setting 777 permissions with no luck).

I've also tried running php artisan optimize, and other commands.

Does anyone have the same error?

**Comment by mbarwick83** [comment]
Hmm, works fine for me (even running L5.2). My php is 7 though. Did you try `composer dumpautoload` on your prod server? Deleting composer.lock and doing `composer update` again may solve...

**Comment by EM-LilianaIturribarria** [comment]
Hi, 
i've followed those steps and no luck.
did you try to use the package on a lower version of php?

**Comment by mbarwick83** [comment]
In the `config/app.php` file, try changing the the facade portion "Mbarwick83" to "mbarwick83". Then run the previous steps I said. You could be right. Might be lower case issue.

**Comment by mbarwick83** [comment]
If http doesn't work, you should be able to use this instead: `use Mbarwick83\Shorty\Shorty`or even put that as the alias - replacing facade path.

**Comment by EM-LilianaIturribarria** [comment]
:( no luck

Class 'Mbarwick83\Shorty\Interfaces\ShortLinkAbstractInterface' not found

**Comment by mbarwick83** [comment]
Does that class actually exist you in your source files?

**Comment by EM-LilianaIturribarria** [comment]
Yes,
and indeed was a problem with case sensitive on linux servers.
it may be the namespace?
I had to use it without composer and now works fine...

**Comment by mbarwick83** [comment]
If you want to submit a pull request. I'll review it

**Comment by tjohnn** [comment]
I had this same issue using L5.2, I installed Shorty locally and re-uploaded my whole project to production server, then it worked.

**Comment by websanova** [comment]
I'm having same issue.

Through facade:

```
Mbarwick83\\Shorty\\Facades\\Shorty' not found
```

Directly with `Mbarwick83\\Shorty\\Shorty`:

```
Class 'Mbarwick83\\Shorty\\Interfaces\\ShortLinkAbstractInterface
```

Seems something wrong with naming, but can't seem to find where or how to fix this.

I'm on Laravel 5.3

**Comment by websanova** [comment]
After getting the packing locally it seems this is indeed is simply a case sensitive issue.

I guess package owner is only testing on windows.

should be like...

```
mbarwick83\Shorty\config
mbarwick83\Shorty\Exceptions
mbarwick83\Shorty\Facades
mbarwick83\Shorty\Interfaces
```

The four folders `shorty`, `exceptions`, `facades`, `interfaces` should be upper cased on first letter.

**Comment by mbarwick83** [comment]
I'm on Mac, and have tested locally and use in prod. Likely a PSR issue for some users. None the less, good catch @websanova, I've made the changes and  committed to the master.
