### ISSUE TITLE
get_headers ... failed to open stream: Connection refused

### ISSUE THREAD

**Issue by hassanazimi** [mbarwick83/shorty#10]
I get this error when I am using the Shorty with Laravel 5.6

<img width="1680" alt="screen shot 2018-04-17 at 12 00 33 pm" src="https://user-images.githubusercontent.com/4809004/38865878-13455904-4237-11e8-8165-7774d4cccf53.png">

Does anyone know why is that happening?

**Comment by cloudstudio** [comment]
I think you don't have a valid url, try just this : 

Shorty::shorten('https://google.com');
