### ISSUE TITLE
The URL provided for shortening is not valid or currently unavailable

### ISSUE THREAD

**Issue by vadimwe** [mbarwick83/shorty#2]
Some urls gives this error. Do you know where may be problem?
Works fine: http://ss.lv
Error: http://webembassy.com/en

![2016-11-07 21 41 44](https://cloud.githubusercontent.com/assets/2635452/20072977/221185e0-a533-11e6-8f18-ebb0e5634c7b.png)

**Comment by mbarwick83** [comment]
Looks like there's some sort of redirect (302) happening on that URL. Likely from the language library I assume? PHP url parser can't valid the url. This issue falls within a very minimal 0.5%. I'm still looking into a work-around, but I don't have time to re-write. So we'll see what I find.

**Comment by mbarwick83** [comment]
Okay, I committed a new release. Got the issue fixed. Please `composer update`. #2

**Comment by mbarwick83** [comment]
https://github.com/mbarwick83/shorty/commit/e68c9304f5398db40b013439731651c690b856e0

**Comment by vadimwe** [comment]
Awesome!!! Thank you for update and nice package!
