### ISSUE TITLE
Shorty::shorten() only works with string literals on L5.3

### ISSUE THREAD

**Issue by elmage** [mbarwick83/shorty#3]
I have tried using the plugin on L5.3, It works if i do `Shorty::shorten('example.com')` but doesn't if i do `Shorty::shorten(route('route-name', $param))` or if i use any function within the `shorten()` method. My browser says "This site can’t be reached, The connection was reset".

**Comment by mbarwick83** [comment]
Of course not. The method doesn't accept functions. Only accepts and checks for strings. All else will fail.  

Save the `route()` to a string variable first, then pass it through and you'll be good.

**Comment by elmage** [comment]
I tried that, still the same error.

**Comment by mbarwick83** [comment]
What's the URL string returning? Does it work without the $param?

**Comment by elmage** [comment]
still does not work... not even if i assign a sting literal to a variable and pass it to the `Shorty::shorten()` function

**Comment by mbarwick83** [comment]
Can you post all your code for this function?

**Comment by elmage** [comment]
`<?php

namespace App\Http\Controllers\News;

use App\Http\Controllers\Controller;
use App\Models\News\News;
use App\Models\ShortUrl;
use Shorty;
use Share;

class NewsController extends Controller
{
	public function index()
	{
		$news = News::with(['images', 'author'])->where('active', 1)->orderBy('id', 'desc')->paginate(15);

		return view('news.index', ['news' => $news]);
	}

	public function show($id)
	{
		$data['news'] = News::where('id', $id)->with(['images', 'author'])->orderBy('id', 'desc')->firstOrFail();

		$data['prev'] = News::where('id', '<', $id)->with(['images', 'author'])->orderBy('id', 'desc')->first();
		$data['next'] = News::where('id', '>', $id)->with(['images', 'author'])->first();

		$data['related'] = News::where('admin_id', $data['news']->admin_id)->with(['images', 'author'])->orderBy('id', 'desc')->limit(4)->get();
        $url = route('news.show', $id);

		$data['services'] = $this->services(route('news.show', $id), $data['news']->title);
        //dd($data['services']);
		return view('news.show', $data);
	}

	public function services($url, $desc)
	{
        /*$link = ShortUrl::with('long_url', $url)->first();
        if($link) {
            return Share::load($link->short_url, $desc)->services();
        } else {
            $short_url = Shorty::shorten($url);
            $new_link = new ShortUrl();
            $new_link->long_url = $url;
            $new_link->short_url = $short_url;
            $new_link->save();

            return Share::load($short_url, $desc)->services();
	}
}`

**Comment by elmage** [comment]
`dd(route('route-name', $param))` shows "http://lyts.dev/show/3"

**Comment by mbarwick83** [comment]
I can't reproduce this issue. Works fine for me on my end. I also tested various routes, including queries and on localhost. No issue or errors.

```
$route = route('index.test', ['lets', 'see']); // http://localhost:8080/testing/lets/see
return Shorty::shorten($route); // i.e. https://goo.gl/S4lS8I
```

**Comment by mbarwick83** [comment]
In your `services()` controller function, you're passing `$url` to it. Just return that and tell me what it is. Is it an actual URL? 

i.e.:

```
public function services($url, $desc)
{
    return $url;
}
```
