### ISSUE TITLE
"ipRefererBlocked" when using key restriction on Google API Credential Setting

### ISSUE THREAD

**Issue by rmdwirizki** [mbarwick83/shorty#5]
`Mbarwick83\Shorty\Exceptions\InvalidApiResponseException with message 'Google Url Shortener returned the following error: [{"domain":"usageLimits","reason":"ipRefererBlocked","message":"The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions.","extendedHelp":"https:\/\/console.developers.google.com\/apis\/credentials?project=177302761668"}]'`

I'm using Laravel 5.4
It works fine when the key restriction menu is set to "none", but the error message showed up if the key restriction setting (_Http referrers_: \*.example.com/\*) was used.

**Comment by mbarwick83** [comment]
How are you initiating the method/class? You shouldn't need to specify key restriction.
