### ISSUE TITLE
Localhost url test

### ISSUE THREAD

**Issue by MarceloBonifazio** [mbarwick83/shorty#9]
Im tryng:

```
$url = 'http://localhost:8000/image-upload';
Shorty::shorten($url);
```
But it does not work, if I try another url other than in localhost, it works...

And in the error log of laravel appears:

> development.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 60 seconds exceeded in ...\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:58
> Stack trace:

**Comment by mbarwick83** [comment]
Of course, it shouldn’t work. URL shortening is handled on Google’s end - and they check for a valid URL, which localhost is not.

**Comment by MarceloBonifazio** [comment]
I find it strange, because testing the api for postman, using the following requisition:

```
curl -X POST \
  'https://www.googleapis.com/urlshortener/v1/url?key=myKey' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: ' \
  -d '{"longUrl": "http://localhost:8000/image-upload"}'
```

It work fine!
The result:

```
{
    "kind": "urlshortener#url",
    "id": "https://goo.gl/xXBeYF",
    "longUrl": "http://localhost:8000/image-upload"
}
```

**Comment by MarceloBonifazio** [comment]
And in fact there is no url validation in the google endpoint, if I try something like:

```
curl -X POST \
   'https://www.googleapis.com/urlshortener/v1/url?key=myKey'
   -H 'cache-control: no-cache' \
   -H 'content-type: application / json' \
   -H 'postman-token: ' \
   -d '{"longUrl": "works"}'
```

It returns me:

```
{
     "kind": "urlshortener # url",
     "id": "https://goo.gl/69huZ",
     "longUrl": "http: // works /"
}
```

**Comment by mbarwick83** [comment]
You can try clearing all referrers in the Google API console. Then it may allow all requests.
